//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xrm.Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xrm.Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- 
        ///// some hard wired properties available from the settings 
        ///{#module_name#}  - name of the parent script module
        ///{#module_notes#}  - description of the template contents
        ///
        ///// Entity metadata property escape syntax
        ///{#ent (property)#}      - raw property name.  Ex: {#ent(IsSLAEnabled)#}
        ///
        ///// Entity metadata property escape syntax
        ///{#attr (property)#}      - raw property name.  Ex: {#ent(AttributeType)#}
        ///
        ///// Both Entity and Attribute metadata objects support these escape methods
        ///{#attr upper(prope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Angular_Xrm_ts_xml {
            get {
                return ResourceManager.GetString("Angular_Xrm_ts_xml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!-- 
        ///// some hard wired properties available from the settings 
        ///{#module_name#}  - name of the parent script module
        ///{#module_notes#}  - description of the template contents
        ///
        ///// Entity metadata property escape syntax
        ///{#ent (property)#}      - raw property name.  Ex: {#ent(IsSLAEnabled)#}
        ///
        ///// Entity metadata property escape syntax
        ///{#attr (property)#}      - raw property name.  Ex: {#ent(AttributeType)#}
        ///
        ///// Both Entity and Attribute metadata objects support these escape methods
        ///{#attr upper(prope [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AxiosTemplate {
            get {
                return ResourceManager.GetString("AxiosTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/jamesnovak/CrmSvcUtilTS/wiki.
        /// </summary>
        internal static string github_help_url {
            get {
                return ResourceManager.GetString("github_help_url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CrmSvcUtilTS.
        /// </summary>
        internal static string github_repo_name {
            get {
                return ResourceManager.GetString("github_repo_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jamesnovak.
        /// </summary>
        internal static string github_user {
            get {
                return ResourceManager.GetString("github_user", resourceCulture);
            }
        }
    }
}
